[package]
name = "zenith-backend"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "zenith-backend"
path = "src/main.rs"

[dependencies]
axum = { version = "0.7", features = ["ws"] }
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5", features = ["cors", "trace", "request-id"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1", features = ["v4"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "migrate"] }
dotenvy = "0.15"
ed25519-dalek = "2"
data-encoding = "2"
rand = "0.8"
tower_governor = "0.4"
regex = "1.13.1"
sha2 = "0.11.0"
opentelemetry = { version = "0.33.0", features = ["trace"], default-features = false }
opentelemetry_sdk = { version = "0.33.0", features = ["rt-tokio", "trace"], default-features = false }
opentelemetry-otlp = { version = "0.33.0", features = ["trace", "grpc-tonic"], default-features = false }
tracing-opentelemetry = { version = "0.34.0", default-features = false }

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
