use crate::signing::SponsorKeyPool;
use serde::{Deserialize, Serialize};
use sqlx::SqlitePool;
use std::collections::HashSet;
use std::sync::{Arc, Mutex};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SponsorshipPolicy {
    pub max_fee_per_tx: i64,        // In stroops (100 stroops = 0.00001 XLM, 1_000_000 stroops = 0.1 XLM)
    pub daily_wallet_budget: i64,   // In stroops
    pub daily_global_budget: i64,   // In stroops
    pub low_watermark_xlm: f64,     // e.g. 50.0 XLM
    pub critical_watermark_xlm: f64,// e.g. 10.0 XLM
}

impl Default for SponsorshipPolicy {
    fn default() -> Self {
        Self {
            max_fee_per_tx: 1_000_000,      // Max 0.1 XLM per transaction
            daily_wallet_budget: 5_000_000, // Max 0.5 XLM per wallet per 24h
            daily_global_budget: 100_000_000,// Max 10.0 XLM global per 24h
            low_watermark_xlm: 50.0,
            critical_watermark_xlm: 10.0,
        }
    }
}

#[derive(Debug, PartialEq, Eq)]
pub enum RelayerError {
    UnauthorizedTransaction,
    FeeExceedsMax(i64, i64),
    WalletDailyBudgetExceeded { current: i64, limit: i64 },
    GlobalDailyBudgetExceeded { current: i64, limit: i64 },
    SponsorshipPausedCriticalBalance { balance_xlm: f64, critical_limit: f64 },
    DatabaseError(String),
}

impl std::fmt::Display for RelayerError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::UnauthorizedTransaction => write!(f, "Transaction rejected: inner tx hash was not generated by Zenith server"),
            Self::FeeExceedsMax(fee, max) => write!(f, "Requested fee {fee} stroops exceeds max allowed {max}"),
            Self::WalletDailyBudgetExceeded { current, limit } => write!(f, "Wallet daily sponsorship budget exhausted ({current}/{limit} stroops)"),
            Self::GlobalDailyBudgetExceeded { current, limit } => write!(f, "Global protocol daily sponsorship budget exhausted ({current}/{limit} stroops)"),
            Self::SponsorshipPausedCriticalBalance { balance_xlm, critical_limit } => write!(f, "Sponsorship paused: sponsor balance ({balance_xlm} XLM) is below critical watermark ({critical_limit} XLM)"),
            Self::DatabaseError(e) => write!(f, "Relayer database error: {e}"),
        }
    }
}

impl std::error::Error for RelayerError {}

pub struct FeeBumpRelayer {
    policy: SponsorshipPolicy,
    key_pool: Arc<SponsorKeyPool>,
    authorized_inner_hashes: Arc<Mutex<HashSet<String>>>,
    db: SqlitePool,
}

impl FeeBumpRelayer {
    pub fn new(policy: SponsorshipPolicy, key_pool: Arc<SponsorKeyPool>, db: SqlitePool) -> Self {
        Self {
            policy,
            key_pool,
            authorized_inner_hashes: Arc::new(Mutex::new(HashSet::new())),
            db,
        }
    }

    /// Registers an authorized inner transaction hash built by the server
    pub fn register_authorized_hash(&self, inner_hash: &str) {
        let mut hashes = self.authorized_inner_hashes.lock().unwrap();
        hashes.insert(inner_hash.to_string());
    }

    /// Validates policy rules, wraps transaction, and records expense
    pub async fn sponsor_and_wrap(
        &self,
        inner_tx_hash: &str,
        inner_tx_xdr: &str,
        wallet_address: &str,
        requested_fee: i64,
        current_sponsor_balance_xlm: f64,
    ) -> Result<String, RelayerError> {
        // 1. Check inner hash is server-authorized
        {
            let hashes = self.authorized_inner_hashes.lock().unwrap();
            if !hashes.contains(inner_tx_hash) {
                return Err(RelayerError::UnauthorizedTransaction);
            }
        }

        // 2. Check max fee limit
        if requested_fee > self.policy.max_fee_per_tx {
            return Err(RelayerError::FeeExceedsMax(requested_fee, self.policy.max_fee_per_tx));
        }

        // 3. Check sponsor balance critical watermark
        if current_sponsor_balance_xlm < self.policy.critical_watermark_xlm {
            return Err(RelayerError::SponsorshipPausedCriticalBalance {
                balance_xlm: current_sponsor_balance_xlm,
                critical_limit: self.policy.critical_watermark_xlm,
            });
        }

        if current_sponsor_balance_xlm < self.policy.low_watermark_xlm {
            tracing::warn!(
                current_balance = current_sponsor_balance_xlm,
                low_watermark = self.policy.low_watermark_xlm,
                "Sponsor balance is below low watermark threshold!"
            );
        }

        // 4. Check wallet 24h budget in DB
        let wallet_used: i64 = sqlx::query_scalar(
            "SELECT COALESCE(SUM(fee_charged), 0) FROM sponsored_transactions 
             WHERE wallet_address = ?1 AND created_at >= datetime('now', '-24 hours')",
        )
        .bind(wallet_address)
        .fetch_one(&self.db)
        .await
        .map_err(|e| RelayerError::DatabaseError(e.to_string()))?;

        if wallet_used + requested_fee > self.policy.daily_wallet_budget {
            return Err(RelayerError::WalletDailyBudgetExceeded {
                current: wallet_used,
                limit: self.policy.daily_wallet_budget,
            });
        }

        // 5. Check global 24h budget in DB
        let global_used: i64 = sqlx::query_scalar(
            "SELECT COALESCE(SUM(fee_charged), 0) FROM sponsored_transactions 
             WHERE created_at >= datetime('now', '-24 hours')",
        )
        .fetch_one(&self.db)
        .await
        .map_err(|e| RelayerError::DatabaseError(e.to_string()))?;

        if global_used + requested_fee > self.policy.daily_global_budget {
            return Err(RelayerError::GlobalDailyBudgetExceeded {
                current: global_used,
                limit: self.policy.daily_global_budget,
            });
        }

        // 6. Sign fee-bump envelope
        let (sponsor_address, _) = self.key_pool.sign_payload(inner_tx_hash.as_bytes());

        // 7. Record transaction in database ledger
        let record_id = uuid::Uuid::new_v4().to_string();
        sqlx::query(
            "INSERT INTO sponsored_transactions (id, inner_tx_hash, wallet_address, sponsor_account, fee_charged, status)
             VALUES (?1, ?2, ?3, ?4, ?5, 'submitted')",
        )
        .bind(&record_id)
        .bind(inner_tx_hash)
        .bind(wallet_address)
        .bind(&sponsor_address)
        .bind(requested_fee)
        .execute(&self.db)
        .await
        .map_err(|e| RelayerError::DatabaseError(e.to_string()))?;

        Ok(format!("FEE_BUMP_ENVELOPE[{sponsor_address}:{requested_fee}:{inner_tx_xdr}]"))
    }
}
