//! Standardized option series registry.
//!
//! A *series* is a canonical, tradable instrument identified by a
//! deterministic instrument ID such as `BTC-27DEC26-70000-C`. Positions
//! reference a series instead of free-form strike/expiry values, which keeps
//! chain data consistent with positions and gives settlement/indexing a single
//! canonical instrument to map to.
//!
//! This module owns:
//!   * strict instrument-ID parsing/formatting (`FromStr`/`Display` round-trip),
//!   * the strike-grid generator (idempotent via `INSERT OR IGNORE`),
//!   * listing/delisting lifecycle helpers.

use std::fmt;
use std::str::FromStr;

use rusqlite::{params, Connection, OptionalExtension};
use serde::{Deserialize, Serialize};

/// Option type (call/put).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum OptionType {
    Call,
    Put,
}

impl OptionType {
    pub fn as_str(&self) -> &'static str {
        match self {
            OptionType::Call => "call",
            OptionType::Put => "put",
        }
    }

    /// Single-letter code used in instrument IDs (`C`/`P`).
    pub fn code(&self) -> char {
        match self {
            OptionType::Call => 'C',
            OptionType::Put => 'P',
        }
    }
}

impl FromStr for OptionType {
    type Err = SeriesError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_ascii_lowercase().as_str() {
            "call" | "c" => Ok(OptionType::Call),
            "put" | "p" => Ok(OptionType::Put),
            other => Err(SeriesError::InvalidType(other.to_string())),
        }
    }
}

/// Lifecycle status of a series.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SeriesStatus {
    Active,
    Delisted,
    Expired,
}

impl SeriesStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            SeriesStatus::Active => "active",
            SeriesStatus::Delisted => "delisted",
            SeriesStatus::Expired => "expired",
        }
    }
}

impl FromStr for SeriesStatus {
    type Err = SeriesError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_ascii_lowercase().as_str() {
            "active" => Ok(SeriesStatus::Active),
            "delisted" => Ok(SeriesStatus::Delisted),
            "expired" => Ok(SeriesStatus::Expired),
            other => Err(SeriesError::InvalidStatus(other.to_string())),
        }
    }
}

/// Standard expiry buckets generated by the registry.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ExpiryBucket {
    Daily,
    Weekly,
    Monthly,
    Quarterly,
}

impl ExpiryBucket {
    pub fn as_str(&self) -> &'static str {
        match self {
            ExpiryBucket::Daily => "daily",
            ExpiryBucket::Weekly => "weekly",
            ExpiryBucket::Monthly => "monthly",
            ExpiryBucket::Quarterly => "quarterly",
        }
    }
}

/// Errors surfaced by the series registry.
#[derive(Debug)]
pub enum SeriesError {
    InvalidInstrumentId(String),
    InvalidType(String),
    InvalidStatus(String),
    UnknownUnderlying(String),
    NotFound(i64),
    NotOpenable { id: i64, status: SeriesStatus },
    Db(rusqlite::Error),
}

impl fmt::Display for SeriesError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            SeriesError::InvalidInstrumentId(s) => {
                write!(f, "invalid instrument id: {s}")
            }
            SeriesError::InvalidType(s) => write!(f, "invalid option type: {s}"),
            SeriesError::InvalidStatus(s) => write!(f, "invalid series status: {s}"),
            SeriesError::UnknownUnderlying(s) => write!(f, "unknown underlying: {s}"),
            SeriesError::NotFound(id) => write!(f, "series {id} not found"),
            SeriesError::NotOpenable { id, status } => write!(
                f,
                "series {id} is {} and cannot be opened",
                status.as_str()
            ),
            SeriesError::Db(e) => write!(f, "database error: {e}"),
        }
    }
}

impl std::error::Error for SeriesError {}

impl From<rusqlite::Error> for SeriesError {
    fn from(e: rusqlite::Error) -> Self {
        SeriesError::Db(e)
    }
}

/// Per-underlying configuration for the strike grid.
#[derive(Debug, Clone, Copy)]
pub struct UnderlyingConfig {
    /// Strike tick size, expressed in the same scaled integer units as strikes.
    pub tick_size: i64,
    /// Grid half-width as a fraction of spot (e.g. 0.30 for ±30%).
    pub grid_half_width: f64,
    /// Grid step as a fraction of spot (e.g. 0.05 for 5% steps).
    pub grid_step: f64,
}

impl UnderlyingConfig {
    /// Default grid: ±30% in 5% steps.
    pub fn default_grid(tick_size: i64) -> Self {
        UnderlyingConfig {
            tick_size,
            grid_half_width: 0.30,
            grid_step: 0.05,
        }
    }
}

/// Resolve the grid configuration for a known underlying.
///
/// XLM trades sub-dollar, so it uses a finer tick size than the majors.
pub fn underlying_config(underlying: &str) -> Result<UnderlyingConfig, SeriesError> {
    match underlying.to_ascii_uppercase().as_str() {
        "BTC" => Ok(UnderlyingConfig::default_grid(1_000)),
        "ETH" => Ok(UnderlyingConfig::default_grid(100)),
        "SOL" => Ok(UnderlyingConfig::default_grid(10)),
        "XLM" => Ok(UnderlyingConfig::default_grid(1)),
        other => Err(SeriesError::UnknownUnderlying(other.to_string())),
    }
}

/// A canonical option series row.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OptionSeries {
    pub id: i64,
    pub underlying: String,
    /// Strike stored as a scaled integer (see `UnderlyingConfig::tick_size`).
    pub strike: i64,
    /// Expiry as a `YYYY-MM-DD` date string.
    pub expiry: String,
    pub option_type: OptionType,
    pub status: SeriesStatus,
    pub instrument_id: String,
}

/// Parsed representation of an instrument ID.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InstrumentId {
    pub underlying: String,
    /// Expiry as `YYYY-MM-DD`.
    pub expiry: String,
    pub strike: i64,
    pub option_type: OptionType,
}

impl fmt::Display for InstrumentId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{}-{}-{}-{}",
            self.underlying.to_ascii_uppercase(),
            format_expiry(&self.expiry),
            self.strike,
            self.option_type.code()
        )
    }
}

impl FromStr for InstrumentId {
    type Err = SeriesError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let parts: Vec<&str> = s.split('-').collect();
        if parts.len() != 4 {
            return Err(SeriesError::InvalidInstrumentId(s.to_string()));
        }
        let underlying = parts[0].to_ascii_uppercase();
        if underlying.is_empty() {
            return Err(SeriesError::InvalidInstrumentId(s.to_string()));
        }
        let expiry = parse_expiry(parts[1])
            .ok_or_else(|| SeriesError::InvalidInstrumentId(s.to_string()))?;
        let strike: i64 = parts[2]
            .parse()
            .map_err(|_| SeriesError::InvalidInstrumentId(s.to_string()))?;
        if strike <= 0 {
            return Err(SeriesError::InvalidInstrumentId(s.to_string()));
        }
        let option_type = parts[3]
            .parse::<OptionType>()
            .map_err(|_| SeriesError::InvalidInstrumentId(s.to_string()))?;
        Ok(InstrumentId {
            underlying,
            expiry,
            strike,
            option_type,
        })
    }
}

/// Format a `YYYY-MM-DD` expiry into the compact `DDMMMYY` form used in IDs.
fn format_expiry(expiry: &str) -> String {
    let parts: Vec<&str> = expiry.split('-').collect();
    if parts.len() != 3 {
        return expiry.to_string();
    }
    let day = parts[2];
    let month = match parts[1] {
        "01" => "JAN",
        "02" => "FEB",
        "03" => "MAR",
        "04" => "APR",
        "05" => "MAY",
        "06" => "JUN",
        "07" => "JUL",
        "08" => "AUG",
        "09" => "SEP",
        "10" => "OCT",
        "11" => "NOV",
        "12" => "DEC",
        _ => return expiry.to_string(),
    };
    let year = if parts[0].len() >= 2 {
        &parts[0][parts[0].len() - 2..]
    } else {
        parts[0]
    };
    format!("{day}{month}{year}")
}

/// Parse a compact `DDMMMYY` expiry back into `YYYY-MM-DD`.
fn parse_expiry(compact: &str) -> Option<String> {
    if compact.len() != 7 {
        return None;
    }
    let day = &compact[0..2];
    let month = match &compact[2..5].to_ascii_uppercase() {
        "JAN" => "01",
        "FEB" => "02",
        "MAR" => "03",
        "APR" => "04",
        "MAY" => "05",
        "JUN" => "06",
        "JUL" => "07",
        "AUG" => "08",
        "SEP" => "09",
        "OCT" => "10",
        "NOV" => "11",
        "DEC" => "12",
        _ => return None,
    };
    let year = &compact[5..7];
    Some(format!("20{year}-{month}-{day}"))
}

/// Build the deterministic instrument ID for a series.
pub fn instrument_id(underlying: &str, expiry: &str, strike: i64, option_type: OptionType) -> String {
    InstrumentId {
        underlying: underlying.to_ascii_uppercase(),
        expiry: expiry.to_string(),
        strike,
        option_type,
    }
    .to_string()
}

/// Round a raw strike to the nearest valid tick for the underlying.
pub fn round_to_tick(strike: i64, tick_size: i64) -> i64 {
    if tick_size <= 0 {
        return strike;
    }
    ((strike + tick_size / 2) / tick_size) * tick_size
}

/// Generate the strike grid for a spot price and underlying config.
///
/// Returns strikes as scaled integers, rounded to the underlying tick size and
/// de-duplicated (rounding can collapse adjacent grid points).
pub fn generate_strikes(spot: f64, cfg: &UnderlyingConfig) -> Vec<i64> {
    let mut strikes = Vec::new();
    let steps = (cfg.grid_half_width / cfg.grid_step).round() as i64;
    for i in -steps..=steps {
        let ratio = 1.0 + (i as f64) * cfg.grid_step;
        if ratio <= 0.0 {
            continue;
        }
        let raw = (spot * ratio).round() as i64;
        let strike = round_to_tick(raw, cfg.tick_size);
        if strike > 0 && !strikes.contains(&strike) {
            strikes.push(strike);
        }
    }
    strikes.sort_unstable();
    strikes
}

/// Generate and persist series for the standard expiry buckets.
///
/// Idempotent: relies on the unique `(underlying, expiry, strike, type)`
/// constraint plus `INSERT OR IGNORE`, so re-running never duplicates rows.
/// Returns the number of newly inserted series.
pub fn generate_series(
    conn: &Connection,
    underlying: &str,
    spot: f64,
    expiries: &[(ExpiryBucket, String)],
) -> Result<usize, SeriesError> {
    let cfg = underlying_config(underlying)?;
    let strikes = generate_strikes(spot, &cfg);
    let mut inserted = 0usize;
    for (_, expiry) in expiries {
        for strike in &strikes {
            for option_type in [OptionType::Call, OptionType::Put] {
                let id = instrument_id(underlying, expiry, *strike, option_type);
                let changed = conn.execute(
                    "INSERT OR IGNORE INTO option_series \
                     (underlying, strike, expiry, option_type, status, instrument_id) \
                     VALUES (?1, ?2, ?3, ?4, 'active', ?5)",
                    params![
                        underlying.to_ascii_uppercase(),
                        strike,
                        expiry,
                        option_type.as_str(),
                        id
                    ],
                )?;
                inserted += changed;
            }
        }
    }
    Ok(inserted)
}

/// Fetch a series by primary key.
pub fn get_series(conn: &Connection, id: i64) -> Result<Option<OptionSeries>, SeriesError> {
    let row = conn
        .query_row(
            "SELECT id, underlying, strike, expiry, option_type, status, instrument_id \
             FROM option_series WHERE id = ?1",
            params![id],
            row_to_series,
        )
        .optional()?;
    Ok(row)
}

/// Fetch a series by its deterministic instrument ID.
pub fn get_series_by_instrument(
    conn: &Connection,
    instrument_id: &str,
) -> Result<Option<OptionSeries>, SeriesError> {
    let row = conn
        .query_row(
            "SELECT id, underlying, strike, expiry, option_type, status, instrument_id \
             FROM option_series WHERE instrument_id = ?1",
            params![instrument_id],
            row_to_series,
        )
        .optional()?;
    Ok(row)
}

/// Resolve a series that is safe to open a new position against.
///
/// Returns `NotOpenable` for `delisted`/`expired` series so callers can map
/// that to HTTP 422.
pub fn resolve_openable_series(conn: &Connection, id: i64) -> Result<OptionSeries, SeriesError> {
    let series = get_series(conn, id)?.ok_or(SeriesError::NotFound(id))?;
    if series.status != SeriesStatus::Active {
        return Err(SeriesError::NotOpenable {
            id,
            status: series.status,
        });
    }
    Ok(series)
}

/// Resolve legacy `(underlying, strike, expiry, type)` fields to an active
/// series, creating it on demand if the grid does not already contain it.
pub fn resolve_or_create_series(
    conn: &Connection,
    underlying: &str,
    strike: i64,
    expiry: &str,
    option_type: OptionType,
) -> Result<OptionSeries, SeriesError> {
    let id = instrument_id(underlying, expiry, strike, option_type);
    if let Some(existing) = get_series_by_instrument(conn, &id)? {
        if existing.status != SeriesStatus::Active {
            return Err(SeriesError::NotOpenable {
                id: existing.id,
                status: existing.status,
            });
        }
        return Ok(existing);
    }
    conn.execute(
        "INSERT OR IGNORE INTO option_series \
         (underlying, strike, expiry, option_type, status, instrument_id) \
         VALUES (?1, ?2, ?3, ?4, 'active', ?5)",
        params![
            underlying.to_ascii_uppercase(),
            strike,
            expiry,
            option_type.as_str(),
            id
        ],
    )?;
    get_series_by_instrument(conn, &id)?.ok_or(SeriesError::NotFound(0))
}

/// List series filtered by optional underlying, expiry and status.
pub fn list_series(
    conn: &Connection,
    underlying: Option<&str>,
    expiry: Option<&str>,
    status: Option<SeriesStatus>,
) -> Result<Vec<OptionSeries>, SeriesError> {
    let mut sql = String::from(
        "SELECT id, underlying, strike, expiry, option_type, status, instrument_id \
         FROM option_series WHERE 1 = 1",
    );
    let mut args: Vec<Box<dyn rusqlite::ToSql>> = Vec::new();
    if let Some(u) = underlying {
        sql.push_str(" AND underlying = ?");
        args.push(Box::new(u.to_ascii_uppercase()));
    }
    if let Some(e) = expiry {
        sql.push_str(" AND expiry = ?");
        args.push(Box::new(e.to_string()));
    }
    if let Some(s) = status {
        sql.push_str(" AND status = ?");
        args.push(Box::new(s.as_str().to_string()));
    }
    sql.push_str(" ORDER BY underlying, expiry, strike, option_type");

    let mut stmt = conn.prepare(&sql)?;
    let params_ref: Vec<&dyn rusqlite::ToSql> = args.iter().map(|b| b.as_ref()).collect();
    let rows = stmt.query_map(params_ref.as_slice(), row_to_series)?;
    let mut out = Vec::new();
    for row in rows {
        out.push(row?);
    }
    Ok(out)
}

/// Delist a series. Existing open interest is preserved; new opens are blocked
/// by `resolve_openable_series`.
pub fn delist_series(conn: &Connection, id: i64) -> Result<OptionSeries, SeriesError> {
    let changed = conn.execute(
        "UPDATE option_series SET status = 'delisted' WHERE id = ?1",
        params![id],
    )?;
    if changed == 0 {
        return Err(SeriesError::NotFound(id));
    }
    get_series(conn, id)?.ok_or(SeriesError::NotFound(id))
}

/// Mark a series expired (used by the settlement engine).
pub fn expire_series(conn: &Connection, id: i64) -> Result<(), SeriesError> {
    conn.execute(
        "UPDATE option_series SET status = 'expired' WHERE id = ?1",
        params![id],
    )?;
    Ok(())
}

/// Count of series, optionally filtered by status.
pub fn count_series(conn: &Connection, status: Option<SeriesStatus>) -> Result<i64, SeriesError> {
    let count = match status {
        Some(s) => conn.query_row(
            "SELECT COUNT(*) FROM option_series WHERE status = ?1",
            params![s.as_str()],
            |r| r.get(0),
        )?,
        None => conn.query_row("SELECT COUNT(*) FROM option_series", [], |r| r.get(0))?,
    };
    Ok(count)
}

fn row_to_series(row: &rusqlite::Row<'_>) -> rusqlite::Result<OptionSeries> {
    let option_type: String = row.get(4)?;
    let status: String = row.get(5)?;
    Ok(OptionSeries {
        id: row.get(0)?,
        underlying: row.get(1)?,
        strike: row.get(2)?,
        expiry: row.get(3)?,
        option_type: option_type.parse().unwrap_or(OptionType::Call),
        status: status.parse().unwrap_or(SeriesStatus::Active),
        instrument_id: row.get(6)?,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn instrument_id_round_trips() {
        let id = instrument_id("BTC", "2026-12-27", 70000, OptionType::Call);
        assert_eq!(id, "BTC-27DEC26-70000-C");
        let parsed: InstrumentId = id.parse().unwrap();
        assert_eq!(parsed.underlying, "BTC");
        assert_eq!(parsed.expiry, "2026-12-27");
        assert_eq!(parsed.strike, 70000);
        assert_eq!(parsed.option_type, OptionType::Call);
        assert_eq!(parsed.to_string(), id);
    }

    #[test]
    fn rejects_malformed_instrument_ids() {
        assert!("BTC-70000-C".parse::<InstrumentId>().is_err());
        assert!("BTC-27DEC26-0-C".parse::<InstrumentId>().is_err());
        assert!("BTC-27DEC26-70000-X".parse::<InstrumentId>().is_err());
    }

    #[test]
    fn strike_grid_respects_tick_and_bounds() {
        let cfg = underlying_config("XLM").unwrap();
        let strikes = generate_strikes(0.42, &cfg);
        assert!(!strikes.is_empty());
        assert!(strikes.iter().all(|s| *s > 0));
        assert!(strikes.windows(2).all(|w| w[0] < w[1]));
    }
}
